# Generated by Django 3.0.5 on 2020-05-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('bio', models.TextField(blank=True)),
                ('fb_link', models.URLField()),
                ('insta_link', models.URLField()),
                ('Linked_in', models.URLField()),
                ('Personal_site', models.URLField()),
                ('html', models.BooleanField(default=False)),
                ('css', models.BooleanField(default=False)),
                ('js', models.BooleanField(default=False)),
                ('python', models.BooleanField(default=False)),
                ('java', models.BooleanField(default=False)),
                ('c', models.BooleanField(default=False)),
                ('c_plus2', models.BooleanField(default=False)),
                ('c_sharp', models.BooleanField(default=False)),
                ('dotnet', models.BooleanField(default=False)),
                ('node', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Degree_name', models.CharField(max_length=100, null=True)),
                ('Institute', models.CharField(max_length=250, null=True)),
                ('date_started', models.DateField()),
                ('date_completed', models.DateField()),
                ('currently', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(max_length=100, null=True)),
                ('tenure', models.CharField(max_length=50, null=True)),
                ('currently_w', models.BooleanField(default=False)),
            ],
        ),
    ]
