# Generated by Django 3.0.5 on 2020-05-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devconnector', '0003_auto_20200523_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='tenure',
        ),
        migrations.AddField(
            model_name='experience',
            name='date_completed_w',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='date_started_w',
            field=models.DateField(null=True),
        ),
    ]
