# Generated by Django 3.0.5 on 2020-05-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devconnector', '0005_auto_20200523_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
