# Generated by Django 3.0.5 on 2020-05-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devconnector', '0007_auto_20200525_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='skills_t',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='skills',
            field=models.CharField(choices=[('skills', 'Select Your skills'), ('front-end', 'Web Designer'), ('django', 'DJANGO'), ('c_sharp', 'ASP .NET'), ('Node', 'NODE'), ('React', 'REACT'), ('Other', 'OTHER')], default='skills', max_length=20),
        ),
    ]
