# Generated by Django 3.0.5 on 2020-05-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devconnector', '0008_auto_20200525_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='skills_t',
        ),
        migrations.AlterField(
            model_name='developer',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
