# Generated by Django 3.0.5 on 2020-05-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devconnector', '0014_auto_20200527_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='p_id',
            field=models.IntegerField(null=True),
        ),
    ]
