# Generated by Django 3.0.5 on 2020-05-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devconnector', '0017_remove_developer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='image',
            field=models.ImageField(null=True, upload_to='devconnector/images'),
        ),
    ]
