# Generated by Django 3.0.5 on 2020-05-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devconnector', '0018_developer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='image',
            field=models.ImageField(default=False, null=True, upload_to='devconnector/images'),
        ),
    ]
