# Generated by Django 3.0.5 on 2020-05-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devconnector', '0020_auto_20200527_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='image',
            field=models.ImageField(blank=True, default='static/devconnector/nopic1.png', null=True, upload_to='devconnector/images'),
        ),
    ]
