# Generated by Django 3.0.5 on 2020-05-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devconnector', '0025_auto_20200527_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='date_completed',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='date_started',
            field=models.DateField(null=True),
        ),
    ]
