# Generated by Django 3.0.5 on 2020-05-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devconnector', '0026_auto_20200528_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
