# Generated by Django 3.0.5 on 2020-05-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devconnector', '0027_developer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='slug',
            field=models.SlugField(default=None, null=True, unique=True),
        ),
    ]
