# Generated by Django 3.0.5 on 2020-05-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devconnector', '0028_auto_20200531_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='slug',
            field=models.SlugField(blank=True, default='name', null=True, unique=True),
        ),
    ]
