# Generated by Django 3.0.5 on 2020-06-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devconnector', '0035_posts_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='disliked',
            field=models.BooleanField(default=0),
        ),
    ]
