# Generated by Django 3.0.5 on 2020-06-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devconnector', '0036_posts_disliked'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='liked_users',
            field=models.TextField(blank=True, null=True),
        ),
    ]
