# Generated by Django 3.0.5 on 2020-06-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devconnector', '0038_auto_20200615_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='date_completed_w',
            field=models.DateField(blank=True, null=True),
        ),
    ]
